import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import sharp from 'sharp';
import { CellDetector } from '../src/detector.js';
import { detectScaleNormalized } from '../src/tiling.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPOS_ROOT = join(__dirname, '..', '..', '..');
const SAMPLE_IMAGE = join(REPOS_ROOT, 'dataset', 'data', 'sample-images', 'IMG_3153.jpeg');
const MODEL_PATH = join(REPOS_ROOT, 'dataset', 'models', 'cell_detector.onnx');
const REF_PATH = join(__dirname, 'fixtures', 'classifier_ref.json');

function median(values) {
	const sorted = [...values].sort((a, b) => a - b);
	const mid = Math.floor(sorted.length / 2);
	return sorted.length % 2 ? sorted[mid] : (sorted[mid - 1] + sorted[mid]) / 2;
}

// dataset is a sibling repo, not checked out by default alongside a clean
// brailleocr checkout -- skip (not error) when its fixtures aren't present,
// rather than letting sharp()/CellDetector.load() throw mid-test.
const FIXTURES_AVAILABLE = existsSync(SAMPLE_IMAGE) && existsSync(MODEL_PATH);
const skipReason = FIXTURES_AVAILABLE
	? false
	: 'requires a sibling `dataset` checkout (sample-images + models) -- not present in this checkout';

async function loadImageAsRgbHwc(path) {
	// .rotate() with no args: auto-orient from EXIF, matching how ultralytics
	// loads images via cv2.imread (which respects EXIF orientation) — see
	// scoping notes on why this matters (letterbox output shape differs
	// entirely between portrait/landscape interpretation of the same file).
	const { data, info } = await sharp(path)
		.rotate()
		.raw()
		.toBuffer({ resolveWithObject: true });
	const rgb = new Float32Array(info.width * info.height * 3);
	for (let i = 0; i < info.width * info.height; i++) {
		rgb[i * 3] = data[i * info.channels];
		rgb[i * 3 + 1] = data[i * info.channels + 1];
		rgb[i * 3 + 2] = data[i * info.channels + 2];
	}
	return { rgb, width: info.width, height: info.height };
}

test('CellDetector matches the Python/ultralytics reference on a real sample image', { skip: skipReason }, async () => {
	const { rgb, width, height } = await loadImageAsRgbHwc(SAMPLE_IMAGE);
	console.log(`Loaded image: ${width}x${height}`);

	const detector = await CellDetector.load(MODEL_PATH);
	const boxes = await detector.detect(rgb, width, height, { confThreshold: 0.15, iouThreshold: 0.7 });

	console.log(`Detected ${boxes.length} boxes (reference: 38)`);
	const top3 = [...boxes].sort((a, b) => b.conf - a.conf).slice(0, 3);
	for (const b of top3) {
		console.log(
			`  cx=${b.cx.toFixed(1)} cy=${b.cy.toFixed(1)} w=${b.w.toFixed(1)} h=${b.h.toFixed(1)} conf=${b.conf.toFixed(3)}`
		);
	}

	// Reference (pipeline.py / ultralytics on cell_detector.onnx, conf=0.15,
	// iou=0.7): 38 boxes, top box xyxy=[2333.5, 2907.9, 2451.3, 3092.5] conf=0.82.
	// This is a RAW single-pass call on both sides — i.e. a JS-vs-Python
	// consistency check for that specific (not realistic) invocation, not a
	// real accuracy measurement. Running the detector on a whole untiled page
	// puts cells far outside the pixel scale it was trained on: box *count*
	// degrades gracefully (which is why this still passes), but box *size*
	// regression does not — a raw single-pass box here is ~3x oversized versus
	// a real single cell (confirmed by cropping the source photo at a box's
	// exact claimed bounds). See the 'detectScaleNormalized' test below for the
	// real accuracy measurement, against correctly-tiled reference boxes.
	// Tolerance of 2 rather than exact equality: this JS port reimplements
	// bilinear resize by hand rather than depending on cv2, so it isn't
	// bit-identical — a handful of borderline candidates right at the conf/IoU
	// threshold can land on either side. pipeline.py's own grid-fill rescue
	// exists precisely because single-box noise like this is expected and
	// tolerated at the orchestration layer, not something the detector itself
	// needs to reproduce exactly.
	assert.ok(
		Math.abs(boxes.length - 38) <= 2,
		`expected ~38 boxes (±2), got ${boxes.length}`
	);

	const refCx = (2333.5 + 2451.3) / 2;
	const refCy = (2907.9 + 3092.5) / 2;
	const match = boxes.find((b) => Math.abs(b.cx - refCx) < 5 && Math.abs(b.cy - refCy) < 5);
	assert.ok(match, `expected a box near (${refCx.toFixed(1)}, ${refCy.toFixed(1)})`);
	assert.ok(Math.abs(match.conf - 0.82) < 0.02, `conf ${match.conf} should be close to 0.82`);
});

test('detectScaleNormalized matches the Python reference in both cell count and box SIZE', { skip: skipReason }, async () => {
	// Unlike the raw single-pass test above, this reference (classifier_ref.json,
	// regenerated by js/test/fixtures/gen_detection_ref.py) comes from
	// pipeline.py's actual tiled + scale-normalized detection path — real,
	// correctly-sized single-cell boxes. This is the test that would have
	// caught the ~3x oversized-box bug the raw single-pass path has.
	const ref = JSON.parse(readFileSync(REF_PATH, 'utf-8'));
	const { rgb, width, height } = await loadImageAsRgbHwc(SAMPLE_IMAGE);
	assert.equal(width, ref.imgW);
	assert.equal(height, ref.imgH);

	const detector = await CellDetector.load(MODEL_PATH);
	const cells = await detectScaleNormalized(detector, rgb, width, height, { confThreshold: 0.15 });

	console.log(`Detected ${cells.length} cells (reference: ${ref.cells.length})`);
	assert.ok(
		Math.abs(cells.length - ref.cells.length) <= ref.cells.length * 0.1,
		`expected ~${ref.cells.length} cells (±10%), got ${cells.length}`
	);

	// Nearest-neighbor match each reference cell to an unclaimed detection —
	// same approach used for the accuracy visualization this test formalizes.
	const avgW = median(ref.cells.map((c) => c.w));
	const used = new Set();
	let matched = 0;
	const matchedWidths = [];
	const matchedHeights = [];
	for (const r of ref.cells) {
		let best = -1;
		let bestDist = Infinity;
		for (let i = 0; i < cells.length; i++) {
			if (used.has(i)) continue;
			const d = Math.hypot(cells[i].cx - r.cx, cells[i].cy - r.cy);
			if (d < bestDist) {
				bestDist = d;
				best = i;
			}
		}
		if (best !== -1 && bestDist < avgW * 0.5) {
			used.add(best);
			matched++;
			matchedWidths.push(cells[best].w);
			matchedHeights.push(cells[best].h);
		}
	}

	const recall = matched / ref.cells.length;
	console.log(`Matched ${matched}/${ref.cells.length} (${(recall * 100).toFixed(1)}%)`);
	assert.ok(recall > 0.9, `expected >90% of reference cells to have a nearby detection, got ${(recall * 100).toFixed(1)}%`);

	// The actual point of this test: box SIZE now agrees, not just position/count.
	const refMedianW = median(ref.cells.map((c) => c.w));
	const refMedianH = median(ref.cells.map((c) => c.h));
	const gotMedianW = median(matchedWidths);
	const gotMedianH = median(matchedHeights);
	console.log(`Median box size — reference: ${refMedianW.toFixed(1)}x${refMedianH.toFixed(1)}, detected: ${gotMedianW.toFixed(1)}x${gotMedianH.toFixed(1)}`);
	assert.ok(
		Math.abs(gotMedianW - refMedianW) / refMedianW < 0.2,
		`median matched width ${gotMedianW.toFixed(1)} should be within 20% of reference ${refMedianW.toFixed(1)}`
	);
	assert.ok(
		Math.abs(gotMedianH - refMedianH) / refMedianH < 0.2,
		`median matched height ${gotMedianH.toFixed(1)} should be within 20% of reference ${refMedianH.toFixed(1)}`
	);
});

test('CellDetector.detect rejects an unexpected output shape before reading candidates from it', async () => {
	// No real model/dataset fixtures needed: CellDetector's constructor takes a
	// session directly, so a fake one exercises the shape-validation path in
	// isolation. Regression test for the shape check running BEFORE (not
	// after) the loop that indexes into raw.data assuming (1, 5, numAnchors).
	const fakeSession = {
		inputNames: ['images'],
		outputNames: ['output0'],
		async run() {
			return { output0: { dims: [1, 6, 10], data: new Float32Array(60) } };
		}
	};
	const detector = new CellDetector(fakeSession);
	const rgb = new Float32Array(4 * 4 * 3);

	await assert.rejects(() => detector.detect(rgb, 4, 4), /Unexpected detector output shape/);
});
